name: evalretro
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - matplotlib=3.8.0
  - numpy=1.26.0
  - pandas=2.1.1
  - pip=23.3
  - python=3.10.13
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - tqdm=4.65.0
  - pip:
      - rdkit-pypi==2022.9.5
      - tensorflow[and-cuda]==2.14.1
      - transformers==4.35.2